# Generated by Django 4.2 on 2025-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('message_data', models.JSONField()),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
